"""empty message

Revision ID: 38948ad9de69
Revises: None
Create Date: 2014-08-21 23:46:54.013000

"""

# revision identifiers, used by Alembic.
revision = '38948ad9de69'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_info',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('facebook_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('moim',
    sa.Column('moim_id', sa.Integer(), nullable=False),
    sa.Column('moim_name', sa.String(length=255), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('moim_id', 'member_id')
    )
    op.create_table('moim_join',
    sa.Column('moim_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=True),
    sa.Column('invited', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('moim_id', 'member_id')
    )
    op.create_table('moim_pay',
    sa.Column('moim_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('payment_all', sa.Integer(), nullable=True),
    sa.Column('moim_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('moim_id', 'number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moim_pay')
    op.drop_table('moim_join')
    op.drop_table('moim')
    op.drop_table('member_info')
    ### end Alembic commands ###
