"""empty message

Revision ID: 3d33436ebc53
Revises: None
Create Date: 2014-08-22 07:14:21.884000

"""

# revision identifiers, used by Alembic.
revision = '3d33436ebc53'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moim_join',
    sa.Column('moim_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('member_name', sa.String(length=255), nullable=True),
    sa.Column('invited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member_info.member_id'], ),
    sa.ForeignKeyConstraint(['moim_id'], ['moim.moim_id'], ),
    sa.PrimaryKeyConstraint('moim_id', 'member_id')
    )
    op.create_table('moim_pay',
    sa.Column('moim_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('payment_all', sa.Integer(), nullable=True),
    sa.Column('moim_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moim_id'], ['moim.moim_id'], ),
    sa.PrimaryKeyConstraint('moim_id', 'number')
    )
    op.create_table('moim_mem',
    sa.Column('moim_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member_info.member_id'], ),
    sa.ForeignKeyConstraint(['moim_id'], ['moim.moim_id'], ),
    sa.PrimaryKeyConstraint('moim_id', 'member_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moim_mem')
    op.drop_table('moim_pay')
    op.drop_table('moim_join')
    ### end Alembic commands ###
